---
# tasks file for setup-cios-server

- name: Upgrade all packages to latest
  ansible.builtin.yum:
    name: "*"
    state: latest
  when: ansible_os_family == 'RedHat'

- name: Install necessary packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  when: ansible_os_family == 'RedHat'
  loop:
    - unzip
    - libaio
    - git

- name: Create directory for instant-client
  ansible.builtin.file:
    path: /opt/oracle
    state: directory

- name: Copy the instant-client archive
  ansible.builtin.copy:
    src: instantclient-basic-linux.x64-12.2.0.1.0.zip
    dest: /opt/oracle

- name: Unzip instant-client
  ansible.builtin.unarchive:
    src: /opt/oracle/instantclient-basic-linux.x64-12.2.0.1.0.zip
    dest: /opt/oracle
    remote_src: yes

- name: Create a symbolic link
  ansible.builtin.file:
    src: "/opt/oracle/instantclient_12_2/{{ item }}.12.1"
    dest: "/opt/oracle/instantclient_12_2/{{ item }}"
    state: link
  loop:
    - libclntsh.so
    - libocci.so

- name: Update the runtime link path
  ansible.builtin.lineinfile:
    path: /etc/ld.so.conf.d/oracle-instantclient.conf
    line: /opt/oracle/instantclient_12_2
    create: yes

- name: Apply the config
  ansible.builtin.shell: ldconfig
