---
galaxy_info:
  author: grzegorznowak
  description: Installs node via nvm globally; includes molecule testing framework.
  company: "Spottmedia Ltd."
  license: "WTFPL"
  role_name: nvm_node
  min_ansible_version: 2.4

  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
        - focal
    - name: Debian
      versions:
        - stretch
        - buster
    - name: EL
      versions:
        - 7
  galaxy_tags: ['node', 'npm', 'nvm', 'molecule']

dependencies: []
