---
dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
platforms:
  - name: ansible-nvm-node-test-20-04
    image: ubuntu/focal/amd64
  - name: ansible-nvm-node-test-18-04
    image: ubuntu/bionic/amd64
  - name: ansible-nvm-node-test-16-04
    image: ubuntu/xenial/amd64
  - name: ansible-nvm-node-test-14-04
    image: ubuntu/trusty/amd64
  - name: ansible-nvm-node-test-buster
    image: debian/buster/amd64
  - name: ansible-nvm-node-test-stretch
    image: debian/stretch/amd64
provisioner:
  config_options:
    defaults:
      bin_ansible_callbacks: true
      display_ok_hosts: false
      display_skipped_hosts: false
      forks: 50
      internal_poll_interval: 0.001
      stdout_callback: yaml
    ssh_connection:
      pipelining: true
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
